package com.unisphere.backend.social.notification.enums;

public enum NotificationType {
    LIKE,
    COMMENT,
    FOLLOW,
    MENTION,
    EVENT,
    JOB,
    MESSAGE,
    ORDER,
    SERVICE_ORDER,
    CLUB_INVITE,
    PROJECT_INVITE,
    MATCH,
    STUDY_SESSION,
    LOST_FOUND_CLAIM,
    VERIFICATION,
    COMMUNITY_ANNOUNCEMENT,
    COMMUNITY_JOIN_REQUEST,
    COMMUNITY_JOIN_APPROVED,
    COMMUNITY_JOIN_REJECTED,
    COMMUNITY_ROLE_CHANGED
}
